const DAYS_PER_WEEK = 7

// Hours
const HOURS_PER_DAY = 24
const HOURS_PER_WEEK = HOURS_PER_DAY * DAYS_PER_WEEK

// Minutes
const MINUTES_PER_HOUR = 60
const MINUTES_PER_DAY = MINUTES_PER_HOUR * HOURS_PER_DAY
const MINUTES_PER_WEEK = MINUTES_PER_HOUR * HOURS_PER_WEEK

// Seconds
const SECONDS_PER_MINUTE = 60
const SECONDS_PER_HOUR = SECONDS_PER_MINUTE * MINUTES_PER_HOUR
const SECONDS_PER_DAY = SECONDS_PER_MINUTE * MINUTES_PER_DAY
const SECONDS_PER_WEEK = SECONDS_PER_MINUTE * MINUTES_PER_WEEK

// Milliseconds
const MILLISECONDS_PER_SECOND = 1000
const MILLISECONDS_PER_MINUTE = MILLISECONDS_PER_SECOND * SECONDS_PER_MINUTE
const MILLISECONDS_PER_HOUR = MILLISECONDS_PER_SECOND * SECONDS_PER_HOUR
const MILLISECONDS_PER_DAY = MILLISECONDS_PER_SECOND * SECONDS_PER_DAY
const MILLISECONDS_PER_WEEK = MILLISECONDS_PER_SECOND * SECONDS_PER_WEEK

export {
  DAYS_PER_WEEK,
  HOURS_PER_DAY,
  HOURS_PER_WEEK,
  MINUTES_PER_HOUR,
  MINUTES_PER_DAY,
  MINUTES_PER_WEEK,
  SECONDS_PER_MINUTE,
  SECONDS_PER_HOUR,
  SECONDS_PER_DAY,
  SECONDS_PER_WEEK,
  MILLISECONDS_PER_SECOND,
  MILLISECONDS_PER_MINUTE,
  MILLISECONDS_PER_HOUR,
  MILLISECONDS_PER_DAY,
  MILLISECONDS_PER_WEEK
}
